apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carstore.fullname" . }}
  labels:
    {{- include "carstore.labels" . | nindent 4 }}
data:
  # Define your configuration data here as key-value pairs
  {{- range $key, $value := .Values.secret }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}