apiVersion: v1
kind: Service
metadata:
  name: {{ include "carstore.fullname" . }}
  labels:
    {{- include "carstore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      #nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "carstore.selectorLabels" . | nindent 4 }}
