annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: '- Fix templating `podManagementPolicy` value in StatefulSet
    configuration of vmselect. See [#807](https://github.com/VictoriaMetrics/helm-charts/pull/807)
    by @MemberIT.'
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html
apiVersion: v1
appVersion: v1.96.0
description: Victoria Metrics Cluster version - high-performance, cost-effective and
  scalable TSDB, long-term remote storage for Prometheus
home: https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
keywords:
- victoriametrics
- vmcluster
- vmselect
- vminsert
- vmstorage
- tsdb
- monitoring
- kubernetes
- observability
- metrics
- metricsql
- timeseries
kubeVersion: '>=v1.22.16'
name: victoria-metrics-cluster
sources:
- https://github.com/VictoriaMetrics/helm-charts
version: 0.11.10
