apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-victoria-metrics-cluster-vmselect
spec:
  resources:
    requests:
      storage: 8G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
